/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CharacterListRouteImport } from './routes/character-list'
import { Route as IndexRouteImport } from './routes/index'

const CharacterListRoute = CharacterListRouteImport.update({
  id: '/character-list',
  path: '/character-list',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/character-list': typeof CharacterListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/character-list': typeof CharacterListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/character-list': typeof CharacterListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/character-list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/character-list'
  id: '__root__' | '/' | '/character-list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharacterListRoute: typeof CharacterListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/character-list': {
      id: '/character-list'
      path: '/character-list'
      fullPath: '/character-list'
      preLoaderRoute: typeof CharacterListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharacterListRoute: CharacterListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
