/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoulsRouteImport } from './routes/souls'
import { Route as MfdRouteImport } from './routes/mfd'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MfdSkillsRouteImport } from './routes/mfd/skills'

const SoulsRoute = SoulsRouteImport.update({
  id: '/souls',
  path: '/souls',
  getParentRoute: () => rootRouteImport,
} as any)
const MfdRoute = MfdRouteImport.update({
  id: '/mfd',
  path: '/mfd',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MfdSkillsRoute = MfdSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => MfdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mfd': typeof MfdRouteWithChildren
  '/souls': typeof SoulsRoute
  '/mfd/skills': typeof MfdSkillsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mfd': typeof MfdRouteWithChildren
  '/souls': typeof SoulsRoute
  '/mfd/skills': typeof MfdSkillsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mfd': typeof MfdRouteWithChildren
  '/souls': typeof SoulsRoute
  '/mfd/skills': typeof MfdSkillsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mfd' | '/souls' | '/mfd/skills'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mfd' | '/souls' | '/mfd/skills'
  id: '__root__' | '/' | '/mfd' | '/souls' | '/mfd/skills'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MfdRoute: typeof MfdRouteWithChildren
  SoulsRoute: typeof SoulsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/souls': {
      id: '/souls'
      path: '/souls'
      fullPath: '/souls'
      preLoaderRoute: typeof SoulsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfd': {
      id: '/mfd'
      path: '/mfd'
      fullPath: '/mfd'
      preLoaderRoute: typeof MfdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfd/skills': {
      id: '/mfd/skills'
      path: '/skills'
      fullPath: '/mfd/skills'
      preLoaderRoute: typeof MfdSkillsRouteImport
      parentRoute: typeof MfdRoute
    }
  }
}

interface MfdRouteChildren {
  MfdSkillsRoute: typeof MfdSkillsRoute
}

const MfdRouteChildren: MfdRouteChildren = {
  MfdSkillsRoute: MfdSkillsRoute,
}

const MfdRouteWithChildren = MfdRoute._addFileChildren(MfdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MfdRoute: MfdRouteWithChildren,
  SoulsRoute: SoulsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
