// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoulsServer.Database;

#nullable disable

namespace SoulsServer.Migrations
{
    [DbContext(typeof(SoulsDbContext))]
    [Migration("20260329131212_MadeSoulTypeAndClassNullable")]
    partial class MadeSoulTypeAndClassNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProficiencySoul", b =>
                {
                    b.Property<int>("ProficienciesId")
                        .HasColumnType("integer");

                    b.Property<int>("SoulsId")
                        .HasColumnType("integer");

                    b.HasKey("ProficienciesId", "SoulsId");

                    b.HasIndex("SoulsId");

                    b.ToTable("ProficiencySoul");
                });

            modelBuilder.Entity("SoulTrait", b =>
                {
                    b.Property<int>("SoulsId")
                        .HasColumnType("integer");

                    b.Property<int>("TraitsId")
                        .HasColumnType("integer");

                    b.HasKey("SoulsId", "TraitsId");

                    b.HasIndex("TraitsId");

                    b.ToTable("SoulTrait");
                });

            modelBuilder.Entity("SoulsServer.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassSoulAbility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("SoulsServer.Models.Proficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Proficiency");
                });

            modelBuilder.Entity("SoulsServer.Models.Soul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Alignment")
                        .HasColumnType("integer");

                    b.Property<int?>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("SoulTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SoulTypeId");

                    b.ToTable("Souls");
                });

            modelBuilder.Entity("SoulsServer.Models.SoulType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("SoulType");
                });

            modelBuilder.Entity("SoulsServer.Models.Trait", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Trait");
                });

            modelBuilder.Entity("ProficiencySoul", b =>
                {
                    b.HasOne("SoulsServer.Models.Proficiency", null)
                        .WithMany()
                        .HasForeignKey("ProficienciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoulsServer.Models.Soul", null)
                        .WithMany()
                        .HasForeignKey("SoulsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoulTrait", b =>
                {
                    b.HasOne("SoulsServer.Models.Soul", null)
                        .WithMany()
                        .HasForeignKey("SoulsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoulsServer.Models.Trait", null)
                        .WithMany()
                        .HasForeignKey("TraitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoulsServer.Models.Soul", b =>
                {
                    b.HasOne("SoulsServer.Models.Class", "Class")
                        .WithMany("Souls")
                        .HasForeignKey("ClassId");

                    b.HasOne("SoulsServer.Models.SoulType", "SoulType")
                        .WithMany("Souls")
                        .HasForeignKey("SoulTypeId");

                    b.Navigation("Class");

                    b.Navigation("SoulType");
                });

            modelBuilder.Entity("SoulsServer.Models.Class", b =>
                {
                    b.Navigation("Souls");
                });

            modelBuilder.Entity("SoulsServer.Models.SoulType", b =>
                {
                    b.Navigation("Souls");
                });
#pragma warning restore 612, 618
        }
    }
}
